/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.chrisle.githubrepoviewer.components;

import javax.swing.JWindow;
import javax.swing.tree.DefaultMutableTreeNode;
import org.chrisle.githubrepoviewer.classes.GithubRepo;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.chrisle.githubrepoviewer.components//GithubRepoViewer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "GithubRepoViewerTopComponent",
        iconBase = "org/chrisle/githubrepoviewer/github.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "org.chrisle.githubrepoviewer.components.GithubRepoViewerTopComponent")
@ActionReferences({
    @ActionReference(path = "Menu/Window" /*, position = 333 */),
    @ActionReference(path = "Shortcuts", name = "DO-G DO-R")
})
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_GithubRepoViewerAction",
        preferredID = "GithubRepoViewerToCpomponent"
)
@Messages({
    "CTL_GithubRepoViewerAction=Github Repository Viewer",
    "CTL_GithubRepoViewerTopComponent=Github Repository Viewer",
    "HINT_GithubRepoViewerTopComponent=This is a Repository Viewer"
})
public final class GithubRepoViewerTopComponent extends TopComponent {
    private GithubRepo _githubRepo;

    public GithubRepoViewerTopComponent() {
        initComponents();
        setName(Bundle.CTL_GithubRepoViewerTopComponent());
        setToolTipText(Bundle.HINT_GithubRepoViewerTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        repositoryTree = new javax.swing.JTree();
        addHost = new javax.swing.JButton();

        jScrollPane1.setViewportView(repositoryTree);

        org.openide.awt.Mnemonics.setLocalizedText(addHost, org.openide.util.NbBundle.getMessage(GithubRepoViewerTopComponent.class, "GithubRepoViewerTopComponent.addHost.text")); // NOI18N
        addHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(addHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addHost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHostActionPerformed
        AddHostDialog hostsDialog = new AddHostDialog(null, true);
        hostsDialog.setVisible(true);
    }//GEN-LAST:event_addHostActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHost;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree repositoryTree;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        _githubRepo = new GithubRepo(new DefaultMutableTreeNode("No hosts available"));

        _githubRepo.fillTreeNodeModel();
        repositoryTree.setModel(_githubRepo.getRepositories());
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
