package org.chrisle.netbeans.modules.gitrepoviewer.components;

/**
 *
 * @author chrl
 */
public class RemoveHostDialog extends javax.swing.JDialog {

    /**
     * Creates new form RemoveHostDialog
     */
    public RemoveHostDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _removeHostLabel = new javax.swing.JLabel();
        _removeHostYes = new javax.swing.JButton();
        _removeHostNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(RemoveHostDialog.class, "RemoveHostDialog.title")); // NOI18N
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setModal(true);
        setName("_removeHostDialog"); // NOI18N
        setResizable(false);

        org.openide.awt.Mnemonics.setLocalizedText(_removeHostLabel, org.openide.util.NbBundle.getMessage(RemoveHostDialog.class, "RemoveHostDialog._removeHostLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(_removeHostYes, org.openide.util.NbBundle.getMessage(RemoveHostDialog.class, "RemoveHostDialog._removeHostYes.text")); // NOI18N
        _removeHostYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _removeHostYesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(_removeHostNo, org.openide.util.NbBundle.getMessage(RemoveHostDialog.class, "RemoveHostDialog._removeHostNo.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(_removeHostYes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(_removeHostNo))
                    .addComponent(_removeHostLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_removeHostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_removeHostYes)
                    .addComponent(_removeHostNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _removeHostYesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        GitRepoViewerTopComponent.removeTreeNode();
        this.setVisible(false);
    }

    private void _removeHostNoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
    }
                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveHostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveHostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveHostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveHostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RemoveHostDialog dialog = new RemoveHostDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _removeHostLabel;
    private javax.swing.JButton _removeHostNo;
    private javax.swing.JButton _removeHostYes;
    // End of variables declaration//GEN-END:variables
}
